Addition of better comments for the Github Enterprise rule.
mozilla-iam/auth0-deploy pull request #383
Opened 2021-09-14 19:40 UTC by rtucker-mozilla

@floatingatoll I've provided better documentation her per your review.
Thanks again for your time!

2021-09-14 21:47 UTC, floatingatoll requested changes

2021-09-14 21:47 UTC, floatingatoll commented on rules/GHE-Groups.js
> +        // End goal is to possibly have conditional endpoint pages on mana that we'll redirect to on and org by or bases.
This is good, but we do need to say something like below, before the details.

`// User is denied access this application, halt sign-in and redirect to help page.`

2021-09-22 20:01 UTC, floatingatoll commented
I get the impression this PR has drifted out of sync. Rob, did we already incorporate this with other PRs?

2021-09-22 20:03 UTC, rtucker-mozilla commented
The file is in it's correct and proper state

2021-09-23 00:01 UTC, floatingatoll commented
Alright, wfm'ing this.

2021-09-23 00:01 UTC, closed without merging