Merge master into production
mozilla-iam/auth0-deploy pull request #425
Opened 2022-11-07 21:34 UTC by dividehex

This PR is identical to https://github.com/mozilla-iam/auth0-deploy/pull/419.  This deployed to the Auth0 Prod tenant.

2022-11-07 22:29 UTC, floatingatoll requested changes

2022-11-07 22:29 UTC, floatingatoll commented on connections/bugzilla.js
> +  request.get('https://bugzilla.allizom.org/api/user/profile', {
This is a dev hostname and likely won't function correctly in prod. I think we need to fetch the prod connections and then merge the Node.js changes into them?

2022-11-07 22:29 UTC, floatingatoll commented on connections/firefoxaccounts.js
> +  request.get('https://profile.stage.mozaws.net/v1/profile', {
This is a stage hostname, see prior concern.

2022-11-07 22:29 UTC, floatingatoll commented on rules/temporary-LDAP-re-reintegration.js
> +function temporaryLDAPReReintergration(user, context, callback) {
Proofreading note: I didn't notice this earlier, but 'Reintegration' is misspelled. It isn't urgent to fix now, but duly noted for later.

2022-11-07 22:38 UTC, floatingatoll commented on connections/bugzilla.js
> +  request.get('https://bugzilla.allizom.org/api/user/profile', {
Per conversation, this is not fully valid — the prod connectors aren't synced yet, and there's no bugzilla connector in prod — however, the entire 'connections/' directory isn't part of any deploy or CI, so this is more like WIP being pulled along so we can update prod to Node.js 12 in a timely manner. Approving review with the understanding that this will be made more consistent.

2022-11-07 22:38 UTC, floatingatoll commented on connections/firefoxaccounts.js
> +  request.get('https://profile.stage.mozaws.net/v1/profile', {
(See prior unconcern.)

2022-11-07 22:38 UTC, floatingatoll approved these changes

2022-11-08 13:43 UTC, dividehex commented
I'll follow up with fixes for these in another PR

2022-11-08 13:44 UTC, merged