Add mozilliansorg_pocket_fin_ops to Pocket section
mozilla-iam/auth0-deploy pull request #484
Opened 2024-11-07 22:40 UTC by bheesham

There's a new group in town: https://people.mozilla.org/a/pocket_fin_ops/

Jira: [IAM-1470](https://mozilla-hub.atlassian.net/browse/IAM-1470)

2024-11-07 22:43 UTC, dividehex requested changes

2024-11-07 22:43 UTC, dividehex commented on rules/awsSaml.js
> +        "mozilliansorg_pocket_fin_ops",
Rules are gone; try actions instead

2024-11-07 22:43 UTC, bheesham commented on rules/awsSaml.js
> +        "mozilliansorg_pocket_fin_ops",
;_;

Whoops

2024-11-07 22:49 UTC, bheesham commented
I went ahead and rebased https://github.com/mozilla-iam/auth0-deploy/pull/481 as well.

2024-11-07 23:07 UTC, dividehex approved these changes
🍒 Approved

2024-11-08 14:32 UTC, bheesham commented
Applied!

2024-11-08 14:32 UTC, merged